# Generated by Django 4.2.30 on 2026-04-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='quantity',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
