# Generated by Django 4.2.7 on 2026-04-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialrequest',
            options={},
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='student_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='request_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='start_date',
            field=models.DateField(),
        ),
    ]
